### PR TITLE
feat:cards and utility classes

### PR DESCRIPTION
**Pull request by TheAmlanSaikia**
Added Cards and some Utility classes.
Cards

### CODE REVIEW

**Review by maitrakhatri — COMMENTED** [review]
everything inside the card has a fixed width and height, won't that be a problem for other people who are using your component lib as their content inside the card will differ and the card won't adjust itself according to it

**Comment by TheAmlanSaikia** [comment]
>  The vertical cards size is okay with all screens but the horizontal cards is scrolling horizontally on small screens.  What do you suggest? Using percentages? or media queries?

**Comment by maitrakhatri** [comment]
> 

well I'm no expert but I personally have given no fixed width, I have used fit-content for almost all cards and vw for horizontal card

**Comment by TheAmlanSaikia** [comment]
> > 
> 
> well I'm no expert but I personally have given no fixed width, I have used fit-content for almost all cards and vw for horizontal card

Below Images are for Iphone SE display

Thanks. Done with the responsiveness. Please check
Responsive cards-horizontal
Cards responsive vertical
.

**Comment by arpit01923** [comment]
Using rem in every element is impressive, ready to go forward

**Review by maitrakhatri — APPROVED** [review]

**Pull request merged**
